name: Alcazar
author: oko
description: Alcazar is a PvP utility plugin, inspired by DevotedPvP.
website: https://oko.moe
version: 2.0.0-alpha.1
main: moe.oko.alcazar.Alcazar
api-version: 1.18
commands:
  inv:
    permission: alcazar.inventory
    description: inv.
    usage: /<command> <save/load> <name>
    aliases: [ inventory ]
  warp:
    permission: alcazar.warp
    description: warp.
    usage: /<command> <name>
    aliases: [ ]
  warps:
    permission: alcazar.warp.management
    description: warps.
    usage: /<command> <save/remove> <name>
    aliases: [ ]
permissions:
  alcazar.admin:
    default: op
  alcazar.inventory:
    default: true